import axios from 'axios';

const api = axios.create({ baseURL: 'https://bigstack-management.vercel.app/api' });
// const api = axios.create({ baseURL: 'http://localhost:3001/api' });

export default api;

// Types
export interface Course {
  id?: number;
  name: string;
  description?: string;
  price?: number;
  duration?: string;
}

export interface Student {
  id?: number;
  sn?: string;        // auto-generated by backend (BST-ST001)
  name: string;
  course: string;
  tutor: string;
  amountPaid: number;
  balance: number;
  feeToPay: number;
  duration: string;
  date: string;
}

export interface ItStudent {
  id?: number;
  sn?: string;        // auto-generated by backend (BST-RG001)
  name: string;
  university: string;
  department: string;
  level: string;
  feeToPay: number;
  amountPaid: number;
  balance: number;
  date: string;
}

export interface HubSubscription {
  id?: number;
  sn?: string;        // auto-generated by backend (BST-HB001)
  name: string;
  amountPaid: number;
  duration: string;
  date: string;
}

export interface FinanceEntry {
  id?: number;
  date: string;
  description: string;
  credit: number;
  debit: number;
  balance: number;
}

export interface KcpEntry {
  _id?: string;
  sn?: string;        // auto-generated by backend (BST-KC001)
  name: string;
  feeToPay: number;
  amountPaid: number;
  balance: number;
  date: string;
  age: string;
}
