import axios from 'axios';

const api = axios.create({ 
  baseURL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api'
});

export default api;

// Types
export interface Course {
  _id?: string;
  name: string;
  description?: string;
  price?: number;
  duration?: string;
}

export interface Student {
  _id?: string;
  sn?: string;        // auto-generated by backend (BST-ST001)
  name: string;
  course: string;
  tutor: string;
  amountPaid: number;
  balance: number;
  feeToPay: number;
  duration: string;
  date: string;
  completed?: boolean;
  certificateIssued?: boolean;
}

export interface ItStudent {
  _id?: string;
  sn?: string;        // auto-generated by backend (BST-RG001)
  name: string;
  university: string;
  department: string;
  level: string;
  feeToPay: number;
  amountPaid: number;
  balance: number;
  date: string;
  completed?: boolean;
  certificateIssued?: boolean;
}

export interface HubSubscription {
  _id?: string;
  sn?: string;        // auto-generated by backend (BST-HB001)
  name: string;
  amountPaid: number;
  duration: string;
  date: string;
}

export interface FinanceEntry {
  _id?: string;
  date: string;
  description: string;
  credit: number;
  debit: number;
  balance: number;
}

export interface KcpEntry {
  _id?: string;
  sn?: string;        // auto-generated by backend (BST-KC001)
  name: string;
  feeToPay: number;
  amountPaid: number;
  balance: number;
  date: string;
  age: string;
  completed?: boolean;
  certificateIssued?: boolean;
}

export interface Staff {
  _id?: string;
  sn?: string;        // auto-generated by backend (BST-SF001)
  firstName: string;
  lastName: string;
  role: string;
  assignedClasses?: string;   // comma-separated list of classes/students this staff handles
  phone?: string;
  email?: string;
  address?: string;
  status?: string;     // Active | Inactive | Suspended
  date: string;        // date of registration
}

export interface Role {
  _id?: string;
  name: string;
  status?: string;
}

export const STAFF_STATUSES = ['Active', 'Inactive', 'Suspended'] as const;
